InsurancePolicyApplication/Models/Category.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InsurancePolicyApplication.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "varchar(100)")]
        [Display(Name = "Category")]
        public string Name { get; set; }
        public virtual List<ContentInsurance> ContentInsurances { get; set; }
    }
}

InsurancePolicyApplication/Models/CommonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InsurancePolicyApplication.Models
{
    public class CommonViewModel
    {
        public ContentInsurance addContent { get; set; }
        public List<ContentInsurance> contentInsurances { get; set; }
    }
}

InsurancePolicyApplication/Models/ContentInsurance.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InsurancePolicyApplication.Models
{
    public class ContentInsurance
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName ="varchar(100)")]
        [Required(ErrorMessage ="Name is Required")]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal Value { get; set; }

        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        [Display(Name = "Category")]
        public virtual Category category { get; set; }


    }
}

InsurancePolicyApplication/Models/DBInitializer.cs
using System.Linq;

namespace InsurancePolicyApplication.Models
{
    public static class DBInitializer
    {
        public static void Initialize(InsurancePolicyDBContext context)
        {
            context.Database.EnsureCreated();

            // Look for any ContentInsurances Table in Database
            if (context.ContentInsurances.Any())
            {
                return; // DB has been seeded
            }

            var categories = new Category[]
            {
            new Category{Name="Electronics"},
            new Category{Name="Clothing"},
            new Category{Name="Kitchen"},
            };
            foreach (Category c in categories)
            {
                context.Categories.Add(c);
            }
            context.SaveChanges();

            var contents = new ContentInsurance[]
            {
                new ContentInsurance{Name="TV", Value=2000, CategoryId=1},
                 new ContentInsurance{Name="Playstation", Value=400, CategoryId=1},
                  new ContentInsurance{Name="Stereo", Value=1600, CategoryId=1},
                   new ContentInsurance{Name="Shirts", Value=1100, CategoryId=2},
                    new ContentInsurance{Name="Jeans", Value=1100, CategoryId=2},
                    new ContentInsurance{Name="Pots and Pans", Value=3000, CategoryId=3},
                    new ContentInsurance{Name="FlatWare", Value=500, CategoryId=3},
                    new ContentInsurance{Name="Knife Set", Value=500, CategoryId=3},
                    new ContentInsurance{Name="Misc", Value=1000, CategoryId=3},
            };
            foreach (ContentInsurance i in contents)
            {
                context.ContentInsurances.Add(i);
            }
            context.SaveChanges();
        }
    }
}

InsurancePolicyApplication/Models/ErrorViewModel.cs
using System;

namespace InsurancePolicyApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InsurancePolicyApplication/Models/IInsurancePolicyService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InsurancePolicyApplication.Models
{
    public interface IInsurancePolicyService
    {
        List<ContentInsurance> GetContentInsurances();
        List<Category> GetCategories();
        void AddContent(ContentInsurance newContent);
        void DeleteContent( int id);
    }
}

InsurancePolicyApplication/Models/InsurancePolicyDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace InsurancePolicyApplication.Models
{
    public class InsurancePolicyDBContext:DbContext
    {
        public InsurancePolicyDBContext(DbContextOptions<InsurancePolicyDBContext> options):base(options)
        {
        }
        public DbSet<ContentInsurance> ContentInsurances { get; set; }
        public DbSet<Category> Categories { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }
}

InsurancePolicyApplication/Models/InsurancePolicyService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace InsurancePolicyApplication.Models
{
    public class InsurancePolicyService : IInsurancePolicyService
    {
        private readonly InsurancePolicyDBContext _context;

        public InsurancePolicyService(InsurancePolicyDBContext context)
        {
            _context = context;
        }
        public void AddContent(ContentInsurance newContent)
        {
            _context.Add(newContent);
            _context.SaveChanges();
        }

        public void DeleteContent(int id)
        {
            var contentInsurance = _context.ContentInsurances.Find(id);
            _context.ContentInsurances.Remove(contentInsurance);
            _context.SaveChanges();
        }

        public List<Category> GetCategories()
        {
            var categories = _context.Categories;
            return categories.ToList();
        }

        public List<ContentInsurance> GetContentInsurances()
        {
            var contentList = _context.ContentInsurances.Include(c => c.category);
            return contentList.ToList();
        }
    }
}

InsurancePolicyApplication/Controllers/ContentInsurancesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsurancePolicyApplication.Models;
using System.Diagnostics;

namespace InsurancePolicyApplication.Controllers
{
    public class ContentInsurancesController : Controller
    {
        private readonly IInsurancePolicyService _policyService;

        public ContentInsurancesController(IInsurancePolicyService policyService)
        {
            _policyService = policyService;
        }

        // GET: ContentInsurances
        public IActionResult Index()
        {
            CommonViewModel model = new CommonViewModel();
            model.addContent = new ContentInsurance();
            model.contentInsurances = _policyService.GetContentInsurances();
            ViewData["CategoryId"] = new SelectList(_policyService.GetCategories(), "Id", "Name");
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CommonViewModel model)
        {
            if (ModelState.IsValid)
            {
                ContentInsurance newContent = new ContentInsurance { Name = model.addContent.Name, Value = model.addContent.Value, CategoryId = model.addContent.CategoryId };
                _policyService.AddContent(newContent);
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_policyService.GetCategories(), "Id", "Name", model.addContent.CategoryId);
            return View(model);
        }

        // GET: ContentInsurances/Delete/5
        public IActionResult Delete(int id)
        {
            _policyService.DeleteContent(id);
            return RedirectToAction(nameof(Index));
        }

        private ContentInsurance ContentInsuranceExists(int id)
        {
            ContentInsurance content = _policyService.GetContentInsurances().Find(c => c.Id == id);
            return content;
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InsurancePolicyApplication/Views/ContentInsurances/Index.cshtml
@model InsurancePolicyApplication.Models.CommonViewModel

@{
    ViewData["Title"] = "Index";
}

<table class="table">
    <tbody>
        @foreach (var group in Model.contentInsurances.GroupBy(i => i.category.Name))
        {
            <tr>
                <th> @Html.DisplayFor(_ => group.Key)</th>
                <td>$@group.Sum(i=>i.Value)</td>
            </tr>
                @foreach (var item in group)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(_ => item.Name)
                    </td>
                    <td>
                        $@Html.DisplayFor(_ => item.Value)
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure to delete this record?')" class="text-secondary"><i class="fa fa-trash fa-lg"></i></a>
                    </td>
                    </tr>
                }
            }

    </tbody>
</table>

<p>
 @using (@Html.BeginForm("Create", "ContentInsurances", FormMethod.Post, new { @class = "form-vertical", role = "form" }))
 {
     @Html.AntiForgeryToken()
   <div class="form-row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-3">
                <input asp-for="addContent.Name" class="form-control" placeholder="Item Name" />
                <span asp-validation-for="addContent.Name" class="text-danger"></span>
            </div>
            <div class="form-group col-md-3">
                <input type="number" value="5000" asp-for="addContent.Value" class="form-control" />
            </div>
            <div class="form-group col-md-3">
                <select asp-for="addContent.CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group col-md-3">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
    </div>
    }
</p>

InsurancePolicyApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Content Insurance Policy Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/3584f80c44.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="ContentInsurances" asp-action="Index">Content Insurance Policy Application</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Content Insurance Policy Application - <a asp-area="" asp-controller="ContentInsurances" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>